apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nxq2dd6vo-go
  janus-idp.io/tekton: nxq2dd6vo-go
  backstage.io/kubernetes-id: nxq2dd6vo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nxq2dd6vo-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
