apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nxq2dd6vo-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nxq2dd6vo-go 
  name: nxq2dd6vo-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nxq2dd6vo-go 
